### PR TITLE
Added EdgeNode to runtimes

### PR DESCRIPTION
**Pull request by mishushakov**
I've added EdgeNode to the front-page in the runtimes section

### CODE REVIEW

**Comment by AlexBlokh** [comment]
hey! what's that? could not find anything on google and neither on your website :/

**Comment by mishushakov** [comment]
Hey, @AlexBlokh 

the website: edgenode.com

it's a upcoming edge/serverless runtime
just want to make sure people know they can use drizzle there too

**Comment by AlexBlokh** [comment]
@mishushakov your discord link is invalid https://discord.com/invite/rGAKFub3
I've applied to early access

**Comment by AlexBlokh** [comment]
I would love to test it fist and then add to the docs

**Pull request closed without merging**
