### PR TITLE
fixed spelling

### PR DESCRIPTION
**Pull request by ShlomoStept**
fixed the spelling of the word 'migtations' to 'migrations'

### CODE REVIEW

**Comment by ShlomoStept** [comment]
I would also like to add a comment below the statement:

```
Learn more about [migration process](https://orm.drizzle.team/docs/migrations). You can also apply migrations using [Supabase CLI](https://supabase.com/docs/guides/cli/getting-started):
``` 

The new version will be:

```
Learn more about [migration process](https://orm.drizzle.team/docs/migrations). You can also apply migrations using [Supabase CLI](https://supabase.com/docs/guides/cli/getting-started):
- For tables that already exist, manually review the generated migration files from `npx drizzle-kit generate` and comment out or adjust any unsafe pure create statements (e.g., `CREATE SCHEMA "auth";`) while ensuring safe conditional creates (e.g., `CREATE TABLE IF NOT EXISTS "auth"."users"`) are properly handled.
```

Longer explanation:

To clarify for Supabase users, tables defined in a schema might be recreated if the "IF NOT EXISTS" clause is not used in the "CREATE" statement. Therefore, if a user defines a table in their code that already exists in Supabase and does not want to recreate it, they must either add "IF NOT EXISTS" to the statement or comment out that code.

For example, if they want to use the built-in Supabase 'users' table under the 'auth' schema, and define the table in their project as follows:

```typescript
import { pgSchema, pgTable, uuid, text, timestamp, jsonb, boolean } from 'drizzle-orm/pg-core'

export const authSchema = pgSchema('auth')

export const users = authSchema.table(
  'users',
  {
    id: uuid('id').primaryKey(),
    aud: text('aud'),
    role: text('role'),
    email: text('email'),
    email_confirmed_at: timestamp('email_confirmed_at'),
    phone: text('phone'),
    phone_confirmed_at: timestamp('phone_confirmed_at'),
    confirmed_at: timestamp('confirmed_at'),
    last_sign_in_at: timestamp('last_sign_in_at'),
    app_metadata: jsonb('app_metadata'),
    user_metadata: jsonb('user_metadata'),
    identities: jsonb('identities'),
    created_at: timestamp('created_at'),
    updated_at: timestamp('updated_at'),
    is_anonymous: boolean('is_anonymous'),
  },
  (table) => {
    return {
      existingTable: true,
    }
  }
)
```

When they run `npx drizzle-kit generate`, it will generate a migration with the SQL code:

```sql
CREATE SCHEMA "auth";
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "auth"."users" (
...
```

In this case, they should comment out the code for `CREATE SCHEMA "auth";` but do not need to comment out the code for `CREATE TABLE IF NOT EXISTS "auth"."users"`, since this will only create the `auth.users` table if it does not already exist.

**Comment by realmikesolo** [comment]
Hello @ShlomoStept. Thank you for your help! Could you please resolve the conflict, so we can merge this PR. We have updated supabase tutorial a bit.

**Comment by ShlomoStept** [comment]
Hi @realmikesolo, I've resolved the conflicts and incorporated the latest updates. The PR is ready for review and merge. Let me know if there's anything else needed. Thanks!

**Comment by realmikesolo** [comment]
@ShlomoStept  Good job, we really appreciate this!

**Pull request merged**
